export const CREATE_MEETUP_REQUEST = '@meetup/CREATE_REQUEST';
export const CREATE_MEETUP_SUCCESS = '@meetup/CREATE_SUCCESS';
export const CREATE_MEETUP_FAILURE = '@meetup/CREATE_FAILURE';
export const UPDATE_MEETUP_REQUEST = '@meetup/UPDATE_REQUEST';
export const UPDATE_MEETUP_SUCCESS = '@meetup/UPDATE_SUCCESS';
export const UPDATE_MEETUP_FAILURE = '@meetup/UPDATE_FAILURE';
